### ISSUE TITLE
Issue loading FortifyClient for 2.6.5

### ISSUE THREAD

**Issue by dblood** [hudson3-plugins/fortify360-plugin#1]
After upgrading jenkins and fortify plugins I found that uploading no longer worked.  I will include both a workaround, and what I believe is the problem.  I know that FortifyClientClassLoader is on the classpath so classes.jar is on the classpath, but loading the nested jar isn't working.

ENVIRONMENT:
Ubuntu Linux 12.04, 64 bit 
Open JDK 64-bit (1.6.0_27)

The error and stack trace:

This occurs when testing the connection in jenkins configuration, as well as when the FPR publisher is run after a build.

java.lang.ClassNotFoundException: org.jvnet.hudson.plugins.fortify360.fortifyclient.FortifyClient
        at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
        at winstone.classLoader.WebappClassLoader.loadClass(WebappClassLoader.java:83)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
        at org.jvnet.hudson.plugins.fortify360.FortifyClientClassLoader.findClass(FortifyClientClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
        at org.jvnet.hudson.plugins.fortify360.FPRPublisher.invokeFortifyClient(FPRPublisher.java:266)
        at org.jvnet.hudson.plugins.fortify360.FPRPublisher.perform(FPRPublisher.java:178)
        at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
        at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:804)
        at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:776)
        at hudson.model.Build$BuildExecution.post2(Build.java:183)
        at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:726)
        at hudson.model.Run.execute(Run.java:1618)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
        at hudson.model.ResourceController.execute(ResourceController.java:88)
        at hudson.model.Executor.run(Executor.java:247)

ANALYSIS:

Line 137 in FortifyClientClassLoader is:
    urls.add(parent.getResource("fortifyclient-" + version + ".jar"));

This is resolving to:
    jar:file:/var/lib/jenkins/plugins/fortify360/WEB-INF/lib/classes.jar!/fortifyclient-2.6.5.jar
I think it should be:
    jar:file:/var/lib/jenkins/plugins/fortify360/WEB-INF/lib/classes.jar^/fortifyclient-2.6.5.jar!/

WORKAROUND:
I extracted the jar from classes.jar, named it fortify-common-3.50.jar and put it in fortify's lib directory.  I then lied to jenkins and said I was running fortify 3.50 so it would include that jar file, and silently ignore that it can't load the jar extract out of classes.jar.

**Comment by lemval** [comment]
See also: https://issues.jenkins-ci.org/browse/JENKINS-21332
