### ISSUE TITLE
java.lang.ClassNotFoundException: org.jvnet.hudson.plugins.fortify360.fortifyclient.FortifyClient

### ISSUE THREAD

**Issue by backslash-f** [hudson3-plugins/fortify360-plugin#2]
Using FPR: file:yadayadayada
Local FPR: file:yadayadayada
Calculated NVS = 133.948440
Saving FPR summary
Uploading FPR to Fortify 360 Server at file:yadayadayada
Error uploading to F360 Server: file:yadayadayada
java.lang.ClassNotFoundException: org.jvnet.hudson.plugins.fortify360.fortifyclient.FortifyClient
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at winstone.classLoader.WebappClassLoader.loadClass(WebappClassLoader.java:83)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at org.jvnet.hudson.plugins.fortify360.FortifyClientClassLoader.findClass(FortifyClientClassLoader.java:196)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at org.jvnet.hudson.plugins.fortify360.FPRPublisher.invokeFortifyClient(FPRPublisher.java:266)
    at org.jvnet.hudson.plugins.fortify360.FPRPublisher.perform(FPRPublisher.java:178)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:804)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:776)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:726)
    at hudson.model.Run.execute(Run.java:1618)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:247)

I added the "yadayadayada", of course.

Jenkins 1.520. Everything up to date, including the Fortify plugin.

Any ideas?

Thanks.

**Comment by backslash-f** [comment]
👋🏻
